FROM node:24-alpine3.21 AS builder

WORKDIR /app
RUN apk add --no-cache git
RUN git clone --depth 1 --branch dev https://github.com/xaker00UA/Frontend-wotblitz.git . && \
    npm install --legacy-peer-deps && \
    npm run build
RUN ls -la


FROM nginx:alpine AS web-server
RUN rm /etc/nginx/conf.d/default.conf

COPY --from=builder /app/dist /static/frontend/
