services:
  cash:
    image : redis:latest
    container_name: cash
    command: ["redis-server", "--maxmemory", "100mb", "--maxmemory-policy", "allkeys-lru"]
  db: 
    image: mongo:latest 
    container_name: mongo
    ports: 
    - "27001:27017"
    mem_limit: 500mb
    volumes:
    - mongo_data:/data/db
  init-db:
    build: 
      context: ../
      dockerfile: docker/Dockerfile.backend
    command: ["python", "-m", "scripts.init_db"]
    env_file:
      - ../.env
    depends_on:
      - db
  backend: 
    build:
      context: ../
      dockerfile: docker/Dockerfile.backend
    container_name: backend
    #Не указывайте user
    depends_on: 
    - db 
    - cash
    env_file:
      - ../.env
    volumes:
     - "./logs:/app/logs"
     - 'media:/app/media'
    mem_limit: 500mb
  nginx:
    container_name: nginx
    build:
      context: .
      dockerfile: Dockerfile.frontend
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
      - media:/static/media
    ports:
      - "80:80"
    depends_on: 
    - backend 
    - db

volumes:
  mongo_data:
  media: