services:
  cash:
    image : redis:latest
    container_name: cash
    command: ["redis-server", "--maxmemory", "500mb", "--maxmemory-policy", "allkeys-lru"]
  db: 
    image: mongo:latest 
    container_name: mongo
    ports: 
    - "27001:27017"
  init-db:
    build: 
      context: ../
      dockerfile: docker/Dockerfile.backend
    command: ["python", "-m", "scripts.init_db"]
    env_file:
      - ../.env
    depends_on:
      - db
  backend: 
    build:
      context: ../
      dockerfile: docker/Dockerfile.backend
    container_name: backend
    depends_on: 
    - db 
    - cash
    env_file:
      - ../.env
    volumes:
     - "./logs:/app/logs"
  frontend:
    build:
      context: ../
      dockerfile: docker/Dockerfile.frontend
    container_name: frontend
    working_dir: /app
    volumes:
      - frontend:/app/dist
  nginx:
    container_name: nginx
    image: nginx:latest
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
      - frontend:/static/frontend
    ports:
      - "80:80"
    depends_on: 
    - backend 
    - db

volumes:
  mongo_data:
  frontend: