FROM python:3.13.3-slim

WORKDIR /app
RUN pip install poetry 
RUN poetry config virtualenvs.create false
COPY ../pyproject.toml ../poetry.lock ./
RUN poetry install --only main --no-root
ADD .. .


EXPOSE 8000


CMD ["uvicorn", "utils.server.app:app", "--host", "0.0.0.0", "--port", "8000","--no-access-log"]