name: Deploy Backend

on:
  workflow_dispatch:
  push:
    branches:
      - master
    tags:
      - '*'

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
      - name: Set up SSH
        uses: webfactory/ssh-agent@v0.5.3
        with:
          ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}
      - name: Add host to known_hosts
        run: ssh-keyscan -H ${{ secrets.EC2_HOST }} >> ~/.ssh/known_hosts
      
      - name: Deploy backend to EC2
        run: |
          ssh ec2-user@${{ secrets.EC2_HOST }} << EOF
            cd app
            rm -rf backend && mkdir -p backend
            cd backend
            git clone -b master https://github.com/${{ github.repository }}.git .
            docker build -t backend:stable .
            cd ../
            docker-compose up  -d --build 
          EOF