name: Build and Deploy Backend

on:
  workflow_dispatch:
  push:
    branches:
      - main
    tags:
      - '*'

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up SSH
        uses: webfactory/ssh-agent@v0.5.3
        with:
          ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}

      - name: Add host to known_hosts
        run: ssh-keyscan -H ${{ secrets.EC2_HOST }} >> ~/.ssh/known_hosts

      - name: Copy code to EC2
        run: rsync -avz --delete ./ ec2-user@${{ secrets.EC2_HOST }}:app/backend

      - name: Deploy to EC2
        run: |
          REF=${{ github.ref }}
          REF_NAME=${{ github.ref_name }}
          ssh ec2-user@${{ secrets.EC2_HOST }} << EOF
            cd /app/backend

            if [[ "$REF" == refs/tags/* ]]; then
              IMAGE_TAG="$REF_NAME"
            else
              IMAGE_TAG="latest"
            fi

            docker build -t backend:\$IMAGE_TAG .
            docker-compose up -d --build backend
          EOF
